# Generated by Django 5.0.3 on 2024-03-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_receipts_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
    ]
