# Generated by Django 5.0.3 on 2024-03-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_receipts_scanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='points_history',
            field=models.IntegerField(default=0),
        ),
    ]
