# Generated by Django 5.0.3 on 2024-04-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_remove_receipt_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='image_identifier',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
